SET SCHEMA DB2INST1;

SELECT LASTNAME, BIRTHDATE
FROM EMPLOYEE
WHERE SEX = 'F'
AND (MOD(YEAR(BIRTHDATE), 4) = 0 AND MOD(YEAR(BIRTHDATE), 100) <> 100)
    OR MOD(YEAR(BIRTHDATE), 400) = 0
ORDER BY BIRTHDATE;

SELECT SEX, EDLEVEL, DECIMAL(ROUND(AVG(SALARY), 0), 8, 0) AS AVG_SAL
FROM EMP
WHERE WORKDEPT = 'E21'
GROUP BY CUBE(SEX, EDLEVEL);

SELECT PROJNAME,
       MONTH(PRENDATE)-MONTH(PRSTDATE) AS MONTHS
FROM PROJECT
WHERE DAYOFWEEK_ISO(PRSTDATE) IN (2)
AND DAYOFWEEK_ISO(PRENDATE) IN (2);


